# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 08:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('JordanLawApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=2500)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ImageField(default='/JordanLawApp/static/images/imgnotfound.png', upload_to='peopleimages/'),
        ),
    ]
