# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-21 08:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JordanLawApp', '0002_auto_20170621_0819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='content',
            field=models.TextField(max_length=2500),
        ),
    ]
