# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-09-07 11:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('JordanLawApp', '0003_auto_20170621_0821'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
